# libxml2
GC33BDB=/opt/gc33bdb
LIBXML2=/usr/local

PATH=$LIBXML2/bin:$PATH
export PATH=$GC33BDB/bin:$PATH

LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=$LIBXML2/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$GC33BDB/lib:$LD_LIBRARY_PATH
