# libxml2 libiconv ncurses
GC33BDB=/opt/gc33bdb
LIBXML2=/opt/homebrew/opt/libxml2
LIBICONV=/opt/homebrew/opt/libiconv
NCURSES=/opt/homebrew/opt/ncurses

PATH=$LIBXML2/bin:$PATH
PATH=$LIBICONV/bin:$PATH
PATH=$NCURSES/bin:$PATH
export PATH=$GC33BDB/bin:$PATH

DYLD_LIBRARY_PATH=.:$DYLD_LIBRARY_PATH
# DYLD_LIBRARY_PATH=$LIBXML2/lib:$DYLD_LIBRARY_PATH
# DYLD_LIBRARY_PATH=$LIBICONV/lib:$DYLD_LIBRARY_PATH
# DYLD_LIBRARY_PATH=$NCURSES/lib:$DYLD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$GC33BDB/lib:$DYLD_LIBRARY_PATH
